In [1]:
import pandas as pd

# Carga de datos

In [2]:
weatherAUS = pd.read_csv('../data/weatherAUS.csv', index_col=[0])

# TAMAÑO DE DATA Y PRIMEROS VISTAZOS

Veamos cúal es el tamaño de data.

In [ ]:
weatherAUS

In [3]:
weatherAUS.head(10)

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
Date,,,,,,,,,,,,,,,,,,,,,
2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,WNW,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,WSW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,WSW,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,E,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,NW,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No
2008-12-06,Albury,14.6,29.7,0.2,NaN,NaN,WNW,56.0,W,W,...,55.0,23.0,1009.2,1005.4,NaN,NaN,20.6,28.9,No,No
2008-12-07,Albury,14.3,25.0,0.0,NaN,NaN,W,50.0,SW,W,...,49.0,19.0,1009.6,1008.2,1.0,NaN,18.1,24.6,No,No
2008-12-08,Albury,7.7,26.7,0.0,NaN,NaN,W,35.0,SSE,W,...,48.0,19.0,1013.4,1010.1,NaN,NaN,16.3,25.5,No,No
2008-12-09,Albury,9.7,31.9,0.0,NaN,NaN,NNW,80.0,SE,NW,...,42.0,9.0,1008.9,1003.6,NaN,NaN,18.3,30.2,No,Yes
2008-12-10,Albury,13.1,30.1,1.4,NaN,NaN,W,28.0,S,SSE,...,58.0,27.0,1007.0,1005.7,NaN,NaN,20.1,28.2,Yes,No